language: ruby

sudo: false

rvm:
  - "2.1"
  - "2.2"
  - "ruby-head"
  - "jruby-9.0.4.0"
  - "jruby-head"
  - "rbx-2.5.8"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

cache: bundler

env:
  - "S3=1 RACK_ENV=development"
