language: ruby

sudo: required
dist: trusty

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.1.15.0
  - jruby-head

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libvips libvips-dev
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

cache: bundler

env:
  - RACK_ENV=development
