language: ruby

sudo: false

rvm:
  - "2.1.8"
  - "2.2.4"
  - "2.3.3"
  - "2.4.0"
  - "ruby-head"
  - "jruby-9.1.7.0"
  - "jruby-head"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

cache: bundler

env:
  - "RACK_ENV=development"
